// <auto-generated />
using System;
using GeoVial.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoVial.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(GeoVialDbContext))]
    [Migration("20260601184741_Captura")]
    partial class Captura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoVial.Domain.Area", b =>
                {
                    b.Property<Guid>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JefeAreaUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AreaId");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.AsignacionAgente", b =>
                {
                    b.Property<Guid>("AsignacionAgenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgenteUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("AsignacionAgenteId");

                    b.HasIndex("RelevamientoId", "AgenteUsuarioId")
                        .IsUnique()
                        .HasDatabaseName("UX_AsignacionAgente");

                    b.ToTable("AsignacionAgente", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Credencial", b =>
                {
                    b.Property<Guid>("CredencialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashClave")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CredencialId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("UX_Credencial_NombreUsuario");

                    b.ToTable("Credencial", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Foto", b =>
                {
                    b.Property<Guid>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Fuente")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("MarcadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObservacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaArchivo")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("TieneMetadatosUbicacion")
                        .HasColumnType("bit");

                    b.HasKey("FotoId");

                    b.HasIndex("ObservacionId")
                        .HasDatabaseName("IX_Foto_Observacion");

                    b.ToTable("Foto", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Marcador", b =>
                {
                    b.Property<Guid>("MarcadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EnConflicto")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MarcadorId");

                    b.HasIndex("RelevamientoId")
                        .HasDatabaseName("IX_Marcador_Relevamiento");

                    b.ToTable("Marcador", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Observacion", b =>
                {
                    b.Property<Guid>("ObservacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgenteUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MarcadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MomentoCaptura")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RelevamientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SinGeorreferenciar")
                        .HasColumnType("bit");

                    b.HasKey("ObservacionId");

                    b.HasIndex("MarcadorId")
                        .HasDatabaseName("IX_Observacion_Marcador");

                    b.HasIndex("RelevamientoId")
                        .HasDatabaseName("IX_Observacion_Relevamiento");

                    b.ToTable("Observacion", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("RegistroAuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecursoAfectado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("RegistroAuditoriaId");

                    b.HasIndex("Momento")
                        .HasDatabaseName("IX_Auditoria_Momento");

                    b.ToTable("RegistroAuditoria", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Relevamiento", b =>
                {
                    b.Property<Guid>("RelevamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<string>("IdentificacionObra")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("RadioAgrupacionMetros")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("RelevamientoId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("IX_Relevamiento_Area");

                    b.ToTable("Relevamiento", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstadoVigencia")
                        .HasColumnType("bit");

                    b.Property<bool>("MetodoSeguridadConfigurado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint")
                        .HasColumnName("RolJerarquico");

                    b.HasKey("UsuarioId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("IX_Usuario_Area");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.AsignacionAgente", b =>
                {
                    b.HasOne("GeoVial.Domain.Relevamiento", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("RelevamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoVial.Domain.Relevamiento", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
