// <auto-generated />
using System;
using GeoVial.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoVial.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(GeoVialDbContext))]
    partial class GeoVialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoVial.Domain.Area", b =>
                {
                    b.Property<Guid>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JefeAreaUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AreaId");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Credencial", b =>
                {
                    b.Property<Guid>("CredencialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashClave")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CredencialId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("UX_Credencial_NombreUsuario");

                    b.ToTable("Credencial", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("RegistroAuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Momento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecursoAfectado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("RegistroAuditoriaId");

                    b.HasIndex("Momento")
                        .HasDatabaseName("IX_Auditoria_Momento");

                    b.ToTable("RegistroAuditoria", (string)null);
                });

            modelBuilder.Entity("GeoVial.Domain.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstadoVigencia")
                        .HasColumnType("bit");

                    b.Property<bool>("MetodoSeguridadConfigurado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Rol")
                        .HasColumnType("tinyint")
                        .HasColumnName("RolJerarquico");

                    b.HasKey("UsuarioId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("IX_Usuario_Area");

                    b.ToTable("Usuario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
