<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GeoVial.Application\GeoVial.Application.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.Domain\GeoVial.Domain.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.Shared\GeoVial.Shared.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.Infrastructure\GeoVial.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.Sync\GeoVial.Sync.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.CapturaCampo\GeoVial.CapturaCampo.csproj" />
    <ProjectReference Include="..\..\src\GeoVial.Revision\GeoVial.Revision.csproj" />
    <ProjectReference Include="..\..\samples\02-sync-maui-demo\SyncDemo.Nucleo\SyncDemo.Nucleo.csproj" />
  </ItemGroup>

</Project>